intro:
title: Contrastive Behavioral Similarity Embeddings for Generalization in Reinforcement Learning
description:
-  Contributed Talk (15 min) at NeurIPS 2020 Workshop on Biological and Artificial RL. 
buttons:
  Paper: 'pdfs/paper.pdf'
  # Code: 'https://github.com/google-research/batch_rl'
  Slides: 'pdfs/slides.pdf'
  Poster: 'pdfs/pse_poster.pdf'
  Contributed Talk: 'https://slideslive.com/38942373' 
  Authors: '#authors'
